EDITOR=nvim
VISUAL=nvim
PAGER=nvimpager
MANPAGER=nvimpager
BROWSER=librewolf
TERM=ghostty
SUDO_EDITOR=nvim
BAT_THEME=ansi
MANROFFOPT=-c
LESSHISTFILE=-
PYTHONSTARTUP=/home/nate/.config/python/pythonrc
XCURSOR_SIZE=24
HYPRCURSOR_SIZE=24
GDK_BACKEND=wayland,x11,*
QT_QPA_PLATFORM=wayland;xcb
MOZ_ENABLE_WAYLAND=1
ELECTRON_OZONE_PLATFORM_HINT=wayland
XDG_SESSION_TYPE=wayland
XDG_CURRENT_DESKTOP=Hyprland
XDG_SESSION_DESKTOP=Hyprland