# 000237-herdr.sh -- herdr (agent multiplexer; keeps coding-agent terminals alive)
# Nix:     .#herdr
# Links:   ~/.config/herdr/config.toml,
#          ~/.config/systemd/user/herdr.service,
#          ~/.claude/skills/herdr/SKILL.md (from the nix profile, not this repo)
#          (~/.config/fish/functions/{hdl,hdlm,hsl,_herdr_*}.fish -- linked by
#           000101-fish's link_tree)
# Enables: herdr.service
# Note: absent from Arch's official repos (0 matching packages), and AUR is
#       excluded by policy, so tier 1 cannot serve it. Upstream DOES publish
#       release binaries behind an install.sh, so this is a deliberate skip past
#       tier 2 as well: that installer floats at latest where flake.lock pins a
#       revision, and the nixpkgs build additionally derives the shell completions
#       and the agent SKILL.md from the binary it just built (see its postInstall)
#       rather than shipping only the executable.
# Note: the unit is authored here because the package ships none, and without one
#       the client daemonizes the server into the cgroup of whichever terminal
#       surface spawned it (observed: app-ghostty-surface-transient-*.scope) --
#       tying a process that owns live agent panes to the lifetime of an
#       unrelated terminal window. Surviving logout or reaching a server before
#       first login additionally needs `loginctl enable-linger`, deliberately NOT
#       done here: agents that keep working unattended are a decision, not a
#       default.
# Note: the skill is linked out of ~/.nix-profile -- not from this repo, and not
#       from /nix/store. The file is generated by the package (`herdr --skill`),
#       so a tracked copy would go stale on upgrade while a store path would pin
#       0.8.2; the profile path repoints on upgrade.
# Note: herdr ships a self-updater (`herdr update`, `herdr channel set`). Do not
#       use it. The binary it would replace lives in the read-only nix store, so
#       an update either fails or lands a second copy outside nix's control --
#       upgrades come from `nix profile upgrade --all` (000600) over a bumped
#       flake.lock.
# Note: config.toml is tracked even though herdr writes it too (`herdr config
#       reset-keys` backs it up and rewrites). A writer that saves by
#       temp-file-then-rename REPLACES the symlink with a real file, after which
#       edits stop reaching this repo silently. Re-running this migration repairs
#       it: link_file backs the stray file up first. The keymap is a tmux-parity
#       port from omarchy; the config's own header explains each binding.

[[ -n "${_COMMON_LOADED:-}" ]] || source "$(dirname "${BASH_SOURCE[0]}")/_common.sh"

section "herdr"

install_nix .#herdr

link_file "$DOTFILES_HOME/.config/herdr/config.toml" "$HOME/.config/herdr/config.toml"
link_file "$DOTFILES_HOME/.config/systemd/user/herdr.service" \
  "$HOME/.config/systemd/user/herdr.service"

# link_file does not check that its source exists, so a missing profile path would
# leave a dangling link that Claude Code reads as a broken skill.
_herdr_skill="$HOME/.nix-profile/share/herdr/skills/herdr/SKILL.md"
if [[ -f "$_herdr_skill" ]]; then
  link_file "$_herdr_skill" "$HOME/.claude/skills/herdr/SKILL.md"
else
  warn "herdr skill not found at $_herdr_skill"
  _add_warning "herdr claude skill not linked; re-run once the nix install lands"
fi

enable_user_service "herdr.service"

ok "herdr"
