# 000322-hyprland-lua.sh -- migrate Hyprland config from hyprlang to Lua
# Installs: (none)
# Links:    ~/.config/hypr/hyprland.lua, ~/.config/hypr/*.lua
#           (re-runs the link_tree from 000310 so the .lua modules are
#           symlinked into the live config; also creates an empty
#           machine-local monitors.lua placeholder)
# Note:     Since Hyprland 0.55 hyprlang is deprecated in favor of Lua
#           (hyprland.lua). hyprland.lua + the flat *.lua modules replace the
#           old hyprland.conf + sourced *.conf files. The modules live flat at
#           the config root (not under lua/). monitors.lua is machine-local
#           (regenerated by nwg-displays) and gitignored, like monitors.conf,
#           so other machines do not pull in these DP port names; this
#           migration creates an empty placeholder so `require("./monitors.lua")`
#           always resolves on a fresh deploy.
#           The one-time transition blocks that removed the old .conf symlinks
#           and the stale lua/ dir, and untracked monitors.lua, have been
#           pruned: every machine has converged and those blocks were
#           permanent no-ops on re-runs and fresh installs alike.

[[ -n "${_COMMON_LOADED:-}" ]] || source "$(dirname "${BASH_SOURCE[0]}")/../_common.sh"

section "hyprland-lua"

# Re-link the tree so the .lua modules get symlinked into the live config.
# (000310 already link_tree's this dir, but re-running here guarantees
#  hyprland.lua + the flat *.lua modules appear even if 000310 ran before
#  this migration existed.)
link_tree "$DOTFILES_HOME/.config/hypr" "$HOME/.config/hypr"

# Machine-local Lua placeholder (real file, NOT a symlink) so the
# `require("./monitors.lua")` call in hyprland.lua always resolves on a fresh
# deploy. nwg-displays overwrites monitors.lua with real monitor data when run.
# (workspaces.lua is tracked in the repo and symlinked by link_tree, so it
# needs no machine-local placeholder.)
for _gen in monitors.lua; do
  _target="$HOME/.config/hypr/$_gen"
  if [[ ! -e "$_target" ]]; then
    : > "$_target"
    info "created empty placeholder: ~/.config/hypr/$_gen (populated by nwg-displays)"
  fi
done

ok "Hyprland Lua config"
