# 000310-hyprland.sh — Hyprland compositor + Wayland ecosystem + config + scripts
# Installs: hyprland hypridle hyprlock hyprpicker hyprsunset hyprpaper
#           hyprpolkitagent hyprlauncher cliphist wayfreeze (local build) uwsm (AUR)
#           xdg-desktop-portal-hyprland xdg-desktop-portal-gtk
#           xdg-desktop-portal-wlr qt5-wayland qt6-wayland resvg
# Links:    ~/.config/hypr/**, ~/.config/systemd/user/hypr-wallpaper.service,
#           ~/.local/bin/{hypr-keybinds,hypr-kill-workspace,hypr-lid-switch,
#             hypr-toggle-display,screenshot,screencast,recording-indicator,
#             toggle-lock,nightmode-toggle,theme-switch,clipboard-manager,
#             power-mode-menu}
# Enables:  hypr-wallpaper.service

[[ -n "${_COMMON_LOADED:-}" ]] || source "$(dirname "${BASH_SOURCE[0]}")/_common.sh"

section "hyprland"

install_pacman \
  hyprland hypridle hyprlock hyprpicker hyprsunset hyprpaper \
  hyprpolkitagent hyprlauncher cliphist \
  xdg-desktop-portal-hyprland xdg-desktop-portal-gtk xdg-desktop-portal-wlr \
  qt5-wayland qt6-wayland resvg
# wayfreeze: build from the upstream 0.2.0 release tag (local PKGBUILD) —
# replaces the former AUR wayfreeze-git. uwsm remains AUR-only (not in scope).
install_aur uwsm
install_local_pkgbuild wayfreeze
ok "Hyprland ecosystem"

link_tree "$DOTFILES_HOME/.config/hypr" "$HOME/.config/hypr"

# hyprland.conf unconditionally `source`s these two files, but they are
# deliberately gitignored — they are machine-specific and regenerated by
# nwg-displays / Hyprland per machine (monitor layout, workspace rules), so
# they must not be tracked in the repo. link_tree only symlinks files that
# exist in the source tree, so on a fresh deploy these are absent and
# Hyprland emits `source= globbing error: found no match` on every launch.
# Create empty placeholder files (real files, NOT symlinks) so the `source`
# always resolves; nwg-displays overwrites monitors.conf with real monitor
# data when run, and Hyprland populates workspaces.conf as workspaces are
# assigned. Touching existing files is a no-op, so this is idempotent.
for _gen in monitors.conf workspaces.conf; do
  _target="$HOME/.config/hypr/$_gen"
  if [[ ! -e "$_target" ]]; then
    : > "$_target"
    info "created empty placeholder: ~/.config/hypr/$_gen (populated by nwg-displays / Hyprland)"
  fi
done

# hypr-wallpaper user service unit
link_file "$DOTFILES_HOME/.config/systemd/user/hypr-wallpaper.service" \
  "$HOME/.config/systemd/user/hypr-wallpaper.service"

# Hyprland helper scripts
for _script in hypr-keybinds hypr-kill-workspace hypr-lid-switch \
  hypr-toggle-display screenshot screencast recording-indicator \
  toggle-lock nightmode-toggle theme-switch clipboard-manager power-mode-menu; do
  link_file "$DOTFILES_HOME/.local/bin/$_script" "$HOME/.local/bin/$_script"
done

enable_user_service "hypr-wallpaper.service"
