# 000322-hyprland-lua.sh -- migrate Hyprland config from hyprlang to Lua
# Installs: (none)
# Links:    ~/.config/hypr/hyprland.lua, ~/.config/hypr/*.lua
#           (via the link_tree already run by 000310; this migration mainly
#           removes the old .conf symlinks and creates machine-local
#           placeholders so hyprland.lua is the active config)
# Note:     Since Hyprland 0.55 hyprlang is deprecated; on 0.56.2 every
#           hyprlang window rule is a no-op. hyprland.lua + the flat *.lua
#           modules replace the old hyprland.conf + sourced *.conf files. hyprlang and Lua do
#           NOT coexist: while hyprland.conf exists, hyprland.lua is ignored,
#           so the old .conf symlinks MUST be removed from the live dir.
#           The modules live flat at the config root (not under lua/);
#           the live lua/ symlink dir from the prior layout is removed.
#           monitors.lua is machine-local (regenerated by nwg-displays) and
#           gitignored, like monitors.conf. It was previously tracked in the
#           repo (this machine's nwg-displays output); it is untracked here
#           so other machines do not pull in these DP port names.

[[ -n "${_COMMON_LOADED:-}" ]] || source "$(dirname "${BASH_SOURCE[0]}")/_common.sh"

section "hyprland-lua"

# Re-link the tree so the new .lua files get symlinked into the live config.
# (000310 already link_tree's this dir, but it only symlinks files present in
#  the source tree at run time; re-running here ensures hyprland.lua + the
#  flat *.lua modules appear even if 000310 ran before this migration existed.)
link_tree "$DOTFILES_HOME/.config/hypr" "$HOME/.config/hypr"

# Remove the stale live lua/ symlink dir from the prior (pre-flatten) layout.
# link_tree only symlinks files that exist in the source tree -- it does NOT
# remove stale symlinks for files no longer present -- so the old
# ~/.config/hypr/lua/*.lua symlinks (now dangling) must be cleared by hand.
# Non-fatal: missing dir is fine (idempotent re-run, fresh deploy).
if [[ -d "$HOME/.config/hypr/lua" ]]; then
  rm -rf "$HOME/.config/hypr/lua"
  info "removed stale live symlink dir: ~/.config/hypr/lua"
fi

# Remove the old hyprlang config symlinks/files from the LIVE config dir so
# Hyprland picks up hyprland.lua instead of falling back to hyprland.conf.
# These are either symlinks into the dotfiles tree (now removed from the
# source) or machine-local gitignored files -- either way, stale here.
# Non-fatal: a missing file is fine (idempotent re-run, fresh deploy).
for _old in hyprland.conf env.conf autostart.conf input.conf looknfeel.conf \
            windows.conf bindings.conf monitors.conf workspaces.conf; do
  _target="$HOME/.config/hypr/$_old"
  if [[ -e "$_target" || -L "$_target" ]]; then
    rm -f "$_target"
    info "removed stale hyprlang file: ~/.config/hypr/$_old"
  fi
done

# Machine-local Lua placeholder (real file, NOT a symlink) so the
# `require("./monitors.lua")` call in hyprland.lua always resolves on a fresh
# deploy. nwg-displays overwrites monitors.lua with real monitor data when run.
# (workspaces.lua is tracked in the repo and symlinked by link_tree, so it
# needs no machine-local placeholder.)
for _gen in monitors.lua; do
  _target="$HOME/.config/hypr/$_gen"
  if [[ ! -e "$_target" ]]; then
    : > "$_target"
    info "created empty placeholder: ~/.config/hypr/$_gen (populated by nwg-displays)"
  fi
done

# Untrack monitors.lua from the repo (it was committed earlier as this
# machine's nwg-displays output). git rm --cached is non-fatal if the file
# is already untracked. The .gitignore addition is done in the same commit
# as this migration; this command just makes the index match.
if git -C "$DOTFILES_ROOT" ls-files --error-unmatch \
     "root/home/.config/hypr/monitors.lua" >/dev/null 2>&1; then
  git -C "$DOTFILES_ROOT" rm --cached --quiet \
     "root/home/.config/hypr/monitors.lua" \
    && info "untracked machine-local root/home/.config/hypr/monitors.lua"
fi

ok "Hyprland Lua config migrated"
