exec-once = systemctl --user import-environment $(env | cut -d= -f1 | tr '\n' ' ')
exec-once = xsettingsd &
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
exec-once = dbus-update-activation-environment --systemd --all
exec-once = sleep 2 && uwsm app -- hyprpaper
exec-once = /home/nate/.config/hypr/set-wallpaper.sh
exec-once = /home/nate/.config/hypr/monitor-watcher.sh

exec-once = uwsm app -- mako
exec-once = uwsm app -- swayosd-server
exec-once = uwsm app -- /usr/lib/hyprpolkitagent/hyprpolkitagent
exec-once = uwsm app -- hypridle
exec-once = uwsm app -- waybar
exec-once = uwsm app -- wl-paste --watch cliphist store