preload = /home/nate/Pictures/wallpapers/yellowstone.jpg
wallpaper {
    monitor = eDP-1
    path = /home/nate/Pictures/wallpapers/yellowstone.jpg
}

wallpaper {
    monitor = DP-5
    path = /home/nate/Pictures/wallpapers/yellowstone.jpg
}

wallpaper {
    monitor = DP-6
    path = /home/nate/Pictures/wallpapers/yellowstone.jpg
}

wallpaper {
    monitor = DP-7
    path = /home/nate/Pictures/wallpapers/yellowstone.jpg
}

splash = false
