# Input device configuration
# See https://wiki.hyprland.org/Configuring/Variables/#input

input {
    kb_layout = us
    kb_options = compose:caps
    follow_mouse = 1
    sensitivity = 0.2

    touchpad {
        natural_scroll = false
        tap-to-click = true
        drag_lock = true
        clickfinger_behavior = true
        middle_button_emulation = true
        disable_while_typing = true
        scroll_factor = 1.0
    }
}

misc {
    key_press_enables_dpms = true
    mouse_move_enables_dpms = true
}

device {
    name = pixa3854:00-093a:0274-mouse
    sensitivity = 0.2
    natural_scroll = false
}

device {
    name = imexps/2-generic-explorer-mouse
    sensitivity = 0.2
    natural_scroll = false
}

# Scroll nicely in the terminal
windowrule = match:class (Alacritty|kitty), scroll_touchpad 1.5
windowrule = match:class com.mitchellh.ghostty, scroll_touchpad 0.2