background-color=#1e1e2e
text-color=#cdd6f4
border-color=#cba6f7
border-radius=0
border-size=0
font=JetBrainsMono Nerd Font 12
width=350
height=110
margin=10
padding=12
default-timeout=5000
ignore-timeout=0

[urgency=high]
border-color=#f38ba8
border-size=2
default-timeout=0
