-- Generated by nwg-displays on 2026-08-22 at 14:06:25. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "2256x1504@60.0",
    position = "3754x1917",
    scale = 1.3333334
})
hl.monitor({
    output = "DP-5",
    mode = "1920x1080@60.0",
    position = "5567x837",
    scale = 1
})
hl.monitor({
    output = "DP-6",
    mode = "1920x1080@60.0",
    position = "1727x837",
    scale = 1
})
hl.monitor({
    output = "DP-7",
    mode = "1920x1080@60.0",
    position = "3647x837",
    scale = 1.0
})
