-- Generated by nwg-displays on 2026-06-01 at 16:46:42. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "2256x1504@60.0",
    position = "3084x1739",
    scale = 1.33
})
hl.monitor({
    output = "DP-8",
    mode = "1920x1080@60.0",
    position = "4891x659",
    scale = 1.0
})
hl.monitor({
    output = "DP-9",
    mode = "1920x1080@60.0",
    position = "2971x659",
    scale = 1.0
})
hl.monitor({
    output = "DP-10",
    mode = "1920x1080@60.0",
    position = "1051x659",
    scale = 1.0
})
