-- Generated by nwg-displays on 2026-07-03 at 10:40:40. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "2256x1504@60.0",
    position = "3754x1917",
    scale = 1.33
})
hl.monitor({
    output = "DP-5",
    mode = "1920x1080@60.0",
    position = "1719x837",
    scale = 1.0
})
hl.monitor({
    output = "DP-6",
    mode = "1920x1080@60.0",
    position = "5567x837",
    scale = 1.0
})
hl.monitor({
    output = "DP-7",
    mode = "1920x1080@60.0",
    position = "3647x837",
    scale = 1.0
})
