windowrule[suppress_event maximize] = class:.*

windowrule[tag +default-opacity] = class:.*

windowrule[opacity 0.97 0.9] = tag:default-opacity

windowrule[opacity 1.0 1.0] = class:^(mpv)$
windowrule[opacity 1.0 1.0] = class:^(vlc)$
windowrule[opacity 1.0 1.0] = class:^(firefox)$
windowrule[opacity 1.0 1.0] = class:^(chromium)$
windowrule[opacity 1.0 1.0] = class:^(google-chrome)$
windowrule[opacity 1.0 1.0] = class:^(obs)$

windowrule[workspace special silent] = title:^(is sharing your screen)

windowrule[nofocus] = class:^$, title:^$, xwayland:1, floating:1, fullscreen:0, pinned:0

windowrule[float] = class:^(imv)$
windowrule[float] = class:^(mpv)$
windowrule[float] = class:^(pavucontrol)$
windowrule[float] = class:^(blueman-manager)$
windowrule[float] = class:^(thunar)$, title:^(Progress|Confirm|Warning|Question)
windowrule[size 875 600] = class:^(imv)$
windowrule[move 50% 50%] = class:^(imv)$, center
windowrule[float] = title:^(Open|Save|File|Folder)$

windowrule[tag +noidle] = class:^(mpv)$
windowrule[tag +noidle] = class:^(zoom)$
windowrule[idleinhibit always] = tag:noidle